[project]
name = "neurovisionai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "p202u", email = "p2002iyush@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
neurovisionai = "neurovisionai:main"

[build-system]
requires = ["uv_build>=0.12.20,<0.13.0"]
build-backend = "uv_build"
