// ============================================================
// ResearchReport.tsx — Exportable Research Report Page
// Neuro-AI Platform · Clinical Research Prototype
// ============================================================

import React, { useState } from 'react';
import { FileText, Printer, Download, CheckCircle, AlertTriangle } from 'lucide-react';
import { apiCreateReport, DEMO_CASES } from '../services/api';
import DisclaimerBanner from '../components/DisclaimerBanner';
import type { ReportData } from '../types';

// ── Print styles injected as a <style> tag ──────────────────
const PRINT_STYLE = `
@media print {
  body { background: #fff !important; color: #111 !important; }
  .sidebar, .main-content > *:not(#report-printable-root), .no-print {
    display: none !important;
  }
  .main-content { margin-left: 0 !important; }
  #report-printable-root { display: block !important; }
  .report-card { box-shadow: none !important; border: 1px solid #ddd !important; background: #fff !important; }
  .report-section-header { color: #1a1a2e !important; border-bottom: 2px solid #e5e7eb !important; }
  .report-table th { color: #374151 !important; background: #f9fafb !important; }
  .report-table td { color: #111 !important; border-bottom: 1px solid #e5e7eb !important; }
  .print-disclaimer { display: block !important; }
  @page { margin: 20mm; size: A4; }
}
`;

// ── Helpers ─────────────────────────────────────────────────

function fmt(n: number, decimals = 4) {
  return n.toFixed(decimals);
}

function fmtTs(iso: string) {
  try {
    return new Date(iso).toLocaleString('en-GB', {
      day: '2-digit', month: 'short', year: 'numeric',
      hour: '2-digit', minute: '2-digit', second: '2-digit',
      timeZoneName: 'short',
    });
  } catch {
    return iso;
  }
}

function diceColor(val: number): string {
  if (val >= 0.85) return '#10B981';
  if (val >= 0.75) return '#F59E0B';
  return '#F43F5E';
}

// ── Sub-components ───────────────────────────────────────────

const SectionHeader: React.FC<{ title: string; accent?: string }> = ({ title, accent = '#F43F5E' }) => (
  <div className="report-section-header" style={{
    display: 'flex', alignItems: 'center', gap: 10,
    borderBottom: `2px solid ${accent}33`,
    paddingBottom: 8, marginBottom: 16, marginTop: 28,
  }}>
    <div style={{ width: 4, height: 20, borderRadius: 2, background: accent, flexShrink: 0 }} />
    <h3 style={{ margin: 0, fontSize: 14, fontWeight: 700, letterSpacing: '-0.01em', color: 'var(--forest)', fontFamily: 'var(--font-serif)' }}>
      {title}
    </h3>
  </div>
);

const ReportTable: React.FC<{
  headers: string[];
  rows: (string | number | React.ReactNode)[][];
}> = ({ headers, rows }) => (
  <div style={{ overflowX: 'auto', borderRadius: 10, border: '1px solid rgba(0,0,0,0.07)' }}>
    <table className="report-table" style={{ width: '100%', borderCollapse: 'collapse', fontSize: 12 }}>
      <thead>
        <tr style={{ background: 'var(--ivory)' }}>
          {headers.map((h, i) => (
            <th key={i} style={{
              padding: '9px 14px', textAlign: 'left',
              fontSize: 10, textTransform: 'uppercase', letterSpacing: '0.08em',
              color: 'var(--sage-light)', fontWeight: 700,
              borderBottom: '1px solid rgba(0,0,0,0.07)',
            }}>{h}</th>
          ))}
        </tr>
      </thead>
      <tbody>
        {rows.map((row, ri) => (
          <tr key={ri}>
            {row.map((cell, ci) => (
              <td key={ci} style={{
                padding: '10px 14px', fontFamily: ci > 0 ? 'var(--font-mono)' : 'var(--font-sans)',
                borderBottom: ri < rows.length - 1 ? '1px solid rgba(0,0,0,0.04)' : 'none',
                color: 'var(--forest)',
              }}>{cell}</td>
            ))}
          </tr>
        ))}
      </tbody>
    </table>
  </div>
);

// ── Full disclaimer texts ────────────────────────────────────

const FULL_DISCLAIMER = `This report is generated by the NeuroAI Research Platform and is strictly intended for research,
academic, and decision-support purposes only. It does NOT constitute a medical diagnosis, clinical report, or therapeutic
recommendation. All AI-generated segmentation masks, reconstruction outputs, and quantitative metrics represent model
predictions derived from a research prototype trained on the BraTS2020 dataset. Outputs have not been validated for
clinical deployment and must not be used as a substitute for qualified radiological, neurological, or clinical judgment.
Any clinical decisions must be made solely by licensed healthcare professionals using approved diagnostic tools and
procedures. Patient safety is paramount — this system is a capstone research demonstration only.`;

const METHODOLOGY_TEXT = `The pipeline employs a Conditional Denoising Diffusion Probabilistic Model (cDDPM) for MRI reconstruction
followed by semi-supervised segmentation using iPixMatch and UniMatch architectures. The DDPM model was trained on the
BraTS2020 multi-modal dataset (T1ce, T2, FLAIR) with 1000 diffusion timesteps. Segmentation models use 10% labeled data
for semi-supervised learning with consistency regularization. Metrics are computed on held-out validation slices using
standard BraTS evaluation criteria: Whole Tumor (WT), Tumor Core (TC), and Enhancing Tumor (ET) Dice coefficients.`;

// ── Main Component ───────────────────────────────────────────

const ResearchReport: React.FC = () => {
  const [selectedCase, setSelectedCase] = useState(DEMO_CASES[0].id);
  const [reportData, setReportData] = useState<ReportData | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const selectedCaseRecord = DEMO_CASES.find(c => c.id === selectedCase) ?? DEMO_CASES[0];

  async function handleGenerate() {
    setIsGenerating(true);
    setError(null);
    try {
      const data = await apiCreateReport(selectedCase);
      setReportData(data);
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : 'Failed to generate report.');
    } finally {
      setIsGenerating(false);
    }
  }

  function handlePrint() {
    window.print();
  }

  // ── Reconstruction metric rows ──────────────────────────────
  const reconRows = reportData?.reconstruction
    ? [
        ['Mean Squared Error (MSE)', fmt(reportData.reconstruction.mse, 6), 'Lower is better', '< 0.002'],
        ['Structural Similarity Index (SSIM)', fmt(reportData.reconstruction.ssim, 4), 'Higher is better', '> 0.50'],
        ['Peak Signal-to-Noise Ratio (PSNR)', `${fmt(reportData.reconstruction.psnr, 4)} dB`, 'Higher is better', '> 28 dB'],
      ]
    : [];

  // ── Segmentation metric rows ────────────────────────────────
  const segRows = reportData?.segmentation
    ? [
        [
          'Whole Tumor (WT)',
          <span style={{ color: '#1A6B4A', fontFamily: 'var(--font-mono)' }}>
            {fmt(reportData.segmentation.dice_wt, 4)}
          </span>,
          `${Math.round(reportData.segmentation.wt_pixels).toLocaleString()} px`,
        ],
        [
          'Tumor Core (TC)',
          <span style={{ color: 'var(--tc-color)', fontFamily: 'var(--font-mono)' }}>
            {fmt(reportData.segmentation.dice_tc, 4)}
          </span>,
          `${Math.round(reportData.segmentation.tc_pixels).toLocaleString()} px`,
        ],
        [
          'Enhancing Tumor (ET)',
          <span style={{ color: 'var(--et-color)', fontFamily: 'var(--font-mono)' }}>
            {fmt(reportData.segmentation.dice_et, 4)}
          </span>,
          `${Math.round(reportData.segmentation.et_pixels).toLocaleString()} px`,
        ],
        [
          <strong>Mean Dice</strong>,
          <span style={{ color: diceColor(reportData.segmentation.mean_dice), fontFamily: 'var(--font-mono)', fontWeight: 700 }}>
            {fmt(reportData.segmentation.mean_dice, 4)}
          </span>,
          '—',
        ],
      ]
    : [];

  return (
    <>
      {/* Injected print styles */}
      <style>{PRINT_STYLE}</style>

      <div className="main-content page-enter" id="report-printable-root">

        {/* ── Top Disclaimer ───────────────────────────────── */}
        <DisclaimerBanner position="top" />

        {/* ── Page Header ──────────────────────────────────── */}
        <div className="no-print" style={{ maxWidth: 1200, margin: '0 auto', padding: '40px 32px 32px' }}>
          <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', flexWrap: 'wrap', gap: 16 }}>
            <div>
              <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 6 }}>
                <div style={{
                  width: 40, height: 40, borderRadius: 12,
                  background: '#80E7B8',
                  display: 'flex', alignItems: 'center', justifyContent: 'center',
                  boxShadow: 'var(--shadow-md)',
                }}>
                  <FileText size={20} color="#fff" />
                </div>
                <div>
                  <h1 className="section-title" style={{ margin: 0, fontFamily: 'var(--font-serif)' }}>
                    Exportable Research Report
                  </h1>
                  <p className="section-subtitle" style={{ margin: 0 }}>
                    AI reconstruction &amp; segmentation pipeline — structured clinical-grade output
                  </p>
                </div>
              </div>
            </div>

            {/* Action Buttons */}
            <div style={{ display: 'flex', gap: 10, flexWrap: 'wrap', alignItems: 'center' }}>
              <button
                className="btn btn-ghost btn-sm"
                onClick={handlePrint}
                disabled={!reportData}
                style={{ opacity: reportData ? 1 : 0.45 }}
              >
                <Printer size={15} />
                Print / Export PDF
              </button>
              <button
                className="btn btn-primary"
                onClick={handleGenerate}
                disabled={isGenerating}
                style={{ opacity: isGenerating ? 0.75 : 1 }}
              >
                {isGenerating ? (
                  <>
                    <div className="spinner" style={{ width: 14, height: 14 }} />
                    Generating…
                  </>
                ) : (
                  <>
                    <Download size={15} />
                    Generate Report
                  </>
                )}
              </button>
            </div>
          </div>

          {/* ── Case Selector ─────────────────────────────── */}
          <div className="glass-card" style={{ padding: '20px 24px', marginTop: 24, marginBottom: 24 }}>
            <p style={{ margin: '0 0 12px', fontSize: 12, color: 'var(--sage-light)', textTransform: 'uppercase', letterSpacing: '0.08em', fontWeight: 700 }}>
              Select Case
            </p>
            <div style={{ display: 'flex', gap: 10, flexWrap: 'wrap' }}>
              {DEMO_CASES.map(c => (
                <button
                  key={c.id}
                  onClick={() => { setSelectedCase(c.id); setReportData(null); setError(null); }}
                  style={{
                    padding: '8px 16px',
                    borderRadius: 10,
                    border: selectedCase === c.id
                      ? '1.5px solid var(--mint-border)'
                      : '1px solid var(--border-glass)',
                    background: selectedCase === c.id
                      ? 'var(--mint)'
                      : 'var(--cream)',
                    color: selectedCase === c.id ? 'var(--forest)' : 'var(--sage)',
                    cursor: 'pointer',
                    fontSize: 13,
                    fontWeight: 600,
                    fontFamily: 'var(--font-sans)',
                    transition: 'all 0.2s',
                  }}
                >
                  {c.label}
                  <span style={{
                    marginLeft: 8, fontSize: 10, padding: '2px 7px',
                    borderRadius: 999,
                    background: c.status === 'done' ? 'rgba(128, 231, 184, 0.35)' : 'rgba(245,158,11,0.15)',
                    color: c.status === 'done' ? '#34D399' : '#FCD34D',
                    fontFamily: 'var(--font-mono)',
                  }}>
                    {c.status}
                  </span>
                </button>
              ))}
            </div>
          </div>

          {/* Error */}
          {error && (
            <div style={{
              display: 'flex', alignItems: 'center', gap: 8,
              padding: '12px 16px', borderRadius: 10, marginBottom: 20,
              background: 'rgba(217, 107, 82, 0.22)', border: '1px solid rgba(217, 107, 82, 0.22)',
              color: '#FB7185', fontSize: 13,
            }}>
              <AlertTriangle size={15} />
              {error}
            </div>
          )}

          {/* Idle state */}
          {!reportData && !isGenerating && !error && (
            <div style={{
              textAlign: 'center', padding: '56px 24px',
              background: 'var(--ivory)', borderRadius: 18,
              border: '1px dashed rgba(217, 107, 82, 0.22)',
              marginBottom: 32,
            }}>
              <FileText size={48} color="rgba(217, 107, 82, 0.22)" style={{ marginBottom: 16 }} />
              <p style={{ margin: '0 0 8px', fontSize: 16, fontWeight: 700, color: 'var(--forest)', fontFamily: 'var(--font-serif)' }}>
                Report not yet generated
              </p>
              <p style={{ margin: 0, fontSize: 13, color: 'var(--sage)' }}>
                Select a case above and click <strong style={{ color: '#FB7185' }}>Generate Report</strong> to preview the exportable research report.
              </p>
            </div>
          )}

          {/* Generating state */}
          {isGenerating && (
            <div style={{
              textAlign: 'center', padding: '56px 24px',
              background: 'var(--ivory)', borderRadius: 18,
              border: '1px solid rgba(217, 107, 82, 0.22)',
              marginBottom: 32,
            }}>
              <div className="spinner" style={{ width: 36, height: 36, margin: '0 auto 16px', borderTopColor: '#F43F5E' }} />
              <p style={{ margin: 0, fontSize: 14, color: 'var(--sage)' }}>
                Assembling report for <strong style={{ color: '#FB7185' }}>{selectedCaseRecord.label}</strong>…
              </p>
            </div>
          )}
        </div>

        {/* ─────────────────────────────────────────────────────── */}
        {/* REPORT PREVIEW — rendered when reportData is available */}
        {/* ─────────────────────────────────────────────────────── */}
        {reportData && (
          <div style={{ maxWidth: 1200, margin: '0 auto', padding: '0 32px 40px' }}>

            {/* Generated confirmation badge */}
            <div className="no-print" style={{
              display: 'flex', alignItems: 'center', gap: 8,
              padding: '10px 16px', borderRadius: 10, marginBottom: 20,
              background: 'rgba(128, 231, 184, 0.35)', border: '1px solid rgba(128, 231, 184, 0.35)',
              color: '#34D399', fontSize: 13, fontWeight: 600,
            }}>
              <CheckCircle size={15} />
              Report generated successfully — {fmtTs(reportData.generated_at)}
            </div>

            {/* ── Report Card (white-bg for print) ─────────── */}
            <div className="report-card glass-card" style={{ padding: '32px 40px', background: '#fff' }}>

              {/* ────── REPORT HEADER ──────────────────────── */}
              <div style={{
                display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between',
                flexWrap: 'wrap', gap: 20,
                paddingBottom: 24, borderBottom: '2px solid rgba(217, 107, 82, 0.22)',
                marginBottom: 8,
              }}>
                {/* Logo + Title */}
                <div style={{ display: 'flex', alignItems: 'center', gap: 14 }}>
                  <div style={{
                    width: 52, height: 52, borderRadius: 14,
                    background: '#80E7B8',
                    display: 'flex', alignItems: 'center', justifyContent: 'center',
                    boxShadow: 'var(--shadow-md)',
                    flexShrink: 0,
                  }}>
                    <FileText size={26} color="#fff" />
                  </div>
                  <div>
                    <div style={{ fontSize: 10, fontWeight: 700, letterSpacing: '0.14em', textTransform: 'uppercase', color: '#F43F5E', marginBottom: 2 }}>
                      NeuroAI Platform · Capstone Research Prototype
                    </div>
                    <h2 style={{ margin: 0, fontSize: 22, fontWeight: 800, letterSpacing: '-0.02em', color: 'var(--forest)', fontFamily: 'var(--font-serif)' }}>
                      MRI Reconstruction &amp; Tumor Segmentation Report
                    </h2>
                    <div style={{ fontSize: 12, color: 'var(--sage)', marginTop: 2 }}>
                      BraTS2020 Multi-Modal Brain Tumor Analysis
                    </div>
                  </div>
                </div>

                {/* Meta block */}
                <div style={{
                  background: 'rgba(217, 107, 82, 0.22)', border: '1px solid rgba(217, 107, 82, 0.22)',
                  borderRadius: 12, padding: '14px 18px', minWidth: 260,
                }}>
                  <div style={{ display: 'grid', gridTemplateColumns: 'auto 1fr', gap: '5px 12px', fontSize: 12 }}>
                    <span style={{ color: 'var(--sage-light)', fontWeight: 600 }}>Case ID</span>
                    <span style={{ fontFamily: 'var(--font-mono)', color: '#FB7185', fontWeight: 600 }}>{reportData.case_id}</span>

                    <span style={{ color: 'var(--sage-light)', fontWeight: 600 }}>Generated</span>
                    <span style={{ fontFamily: 'var(--font-mono)', color: 'var(--forest)', fontSize: 11 }}>{fmtTs(reportData.generated_at)}</span>

                    <span style={{ color: 'var(--sage-light)', fontWeight: 600 }}>DDPM Model</span>
                    <span style={{ fontFamily: 'var(--font-mono)', color: 'var(--cyan)', fontSize: 11 }}>{reportData.model_versions.ddpm}</span>

                    <span style={{ color: 'var(--sage-light)', fontWeight: 600 }}>Seg Model</span>
                    <span style={{ fontFamily: 'var(--font-mono)', color: 'var(--tc-color)', fontSize: 11 }}>{reportData.model_versions.segmentation}</span>
                  </div>
                  <div style={{
                    marginTop: 10, padding: '6px 10px', borderRadius: 6,
                    background: 'rgba(128, 231, 184, 0.35)', border: '1px solid rgba(128, 231, 184, 0.35)',
                    fontSize: 10, color: '#34D399', fontWeight: 600, letterSpacing: '0.06em',
                  }}>
                    ✓ DE-IDENTIFIED · RESEARCH USE ONLY
                  </div>
                </div>
              </div>

              {/* ────── DISCLAIMER INLINE ──────────────────── */}
              <DisclaimerBanner position="inline" />

              {/* ────── EXECUTIVE SUMMARY ──────────────────── */}
              <SectionHeader title="Executive Summary" accent="#F43F5E" />
              <div style={{
                background: 'var(--ivory)', border: '1px solid rgba(0,0,0,0.06)',
                borderRadius: 10, padding: '16px 20px', fontSize: 13, lineHeight: 1.8,
                color: 'var(--sage)',
              }}>
                {reportData.reconstruction && reportData.segmentation ? (
                  <>
                    Analysis of case <strong style={{ color: '#FB7185', fontFamily: 'var(--font-mono)' }}>{reportData.case_id}</strong> was
                    completed successfully using the full NeuroAI pipeline. The Conditional DDPM reconstruction model ({reportData.model_versions.ddpm}) achieved
                    a <strong style={{ color: 'var(--cyan)' }}>PSNR of {fmt(reportData.reconstruction.psnr, 2)} dB</strong> and{' '}
                    <strong style={{ color: 'var(--cyan)' }}>SSIM of {fmt(reportData.reconstruction.ssim, 4)}</strong> on the T1ce/T2/FLAIR MRI slices,
                    confirming high-fidelity denoising with minimal structural distortion (MSE = {fmt(reportData.reconstruction.mse, 6)}).
                    Downstream segmentation using {reportData.model_versions.segmentation} (Experiment&nbsp;
                    {reportData.segmentation.experiment}) on the DDPM-reconstructed input yielded a{' '}
                    <strong style={{ color: 'var(--tc-color)' }}>Mean Dice of {fmt(reportData.segmentation.mean_dice, 4)}</strong>{' '}
                    across three tumor sub-regions: Whole Tumor ({fmt(reportData.segmentation.dice_wt, 4)}),
                    Tumor Core ({fmt(reportData.segmentation.dice_tc, 4)}), and Enhancing Tumor ({fmt(reportData.segmentation.dice_et, 4)}).
                    Results confirm that diffusion-based reconstruction consistently improves downstream segmentation fidelity
                    relative to the original MRI baseline (Experiment&nbsp;A).
                  </>
                ) : (
                  <span style={{ color: 'var(--sage-light)' }}>Partial pipeline data — some stages may not have completed for this case.</span>
                )}
              </div>

              {/* ────── RECONSTRUCTION RESULTS ─────────────── */}
              <SectionHeader title="Reconstruction Results — Conditional DDPM" accent="#1F7A58" />
              {reportData.reconstruction ? (
                <>
                  <div style={{ display: 'flex', gap: 10, flexWrap: 'wrap', marginBottom: 16 }}>
                    {[
                      { label: 'Model', value: reportData.reconstruction.model_version, color: 'var(--cyan)' },
                      { label: 'Timesteps', value: `T = 1000`, color: 'var(--blue)' },
                      { label: 'Preprocessing', value: 'v1.0 · Skull-strip + Z-norm', color: 'var(--sage)' },
                      { label: 'Completed', value: fmtTs(reportData.reconstruction.timestamp), color: 'var(--sage-light)' },
                    ].map(({ label, value, color }) => (
                      <div key={label} style={{
                        padding: '8px 14px', borderRadius: 8,
                        background: 'rgba(128, 231, 184, 0.35)', border: '1px solid rgba(128, 231, 184, 0.35)',
                        fontSize: 11,
                      }}>
                        <span style={{ color: 'var(--sage-light)', marginRight: 6, fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.06em' }}>{label}:</span>
                        <span style={{ color, fontFamily: 'var(--font-mono)', fontWeight: 500 }}>{value}</span>
                      </div>
                    ))}
                  </div>
                  <ReportTable
                    headers={['Metric', 'Value', 'Interpretation', 'Threshold']}
                    rows={reconRows}
                  />
                </>
              ) : (
                <p style={{ color: 'var(--sage-light)', fontSize: 13 }}>Reconstruction data unavailable for this case.</p>
              )}

              {/* ────── SEGMENTATION RESULTS ───────────────── */}
              <SectionHeader title="Segmentation Results — Tumor Sub-Regions" accent="#10B981" />
              {reportData.segmentation ? (
                <>
                  <div style={{ display: 'flex', gap: 10, flexWrap: 'wrap', marginBottom: 16 }}>
                    {[
                      {
                        label: 'Experiment',
                        value: `Experiment ${reportData.segmentation.experiment} — ${reportData.segmentation.input_source === 'reconstructed' ? 'DDPM Reconstructed Input' : 'Original MRI Input'}`,
                        color: reportData.segmentation.experiment === 'B' ? 'var(--tc-color)' : 'var(--amber)',
                      },
                      { label: 'Model', value: reportData.segmentation.model_version, color: 'var(--tc-color)' },
                      { label: 'Completed', value: fmtTs(reportData.segmentation.timestamp), color: 'var(--sage-light)' },
                    ].map(({ label, value, color }) => (
                      <div key={label} style={{
                        padding: '8px 14px', borderRadius: 8,
                        background: 'rgba(128, 231, 184, 0.35)', border: '1px solid rgba(128, 231, 184, 0.35)',
                        fontSize: 11,
                      }}>
                        <span style={{ color: 'var(--sage-light)', marginRight: 6, fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.06em' }}>{label}:</span>
                        <span style={{ color, fontFamily: 'var(--font-mono)', fontWeight: 500 }}>{value}</span>
                      </div>
                    ))}
                  </div>
                  <ReportTable
                    headers={['Sub-Region', 'Dice Score', 'Voxel Count']}
                    rows={segRows}
                  />
                  {/* Legend */}
                  <div style={{ display: 'flex', gap: 16, marginTop: 12, flexWrap: 'wrap' }}>
                    {[
                      { color: '#10B981', label: '>= 0.85 — Excellent' },
                      { color: '#F59E0B', label: '0.75–0.84 — Good' },
                      { color: '#F43F5E', label: '< 0.75 — Needs review' },
                    ].map(({ color, label }) => (
                      <div key={label} style={{ display: 'flex', alignItems: 'center', gap: 6, fontSize: 11, color: 'var(--sage-light)' }}>
                        <div style={{ width: 10, height: 10, borderRadius: 2, background: color }} />
                        {label}
                      </div>
                    ))}
                  </div>
                </>
              ) : (
                <p style={{ color: 'var(--sage-light)', fontSize: 13 }}>Segmentation data unavailable for this case.</p>
              )}

              {/* ────── CLINICAL SAFETY ────────────────────── */}
              <SectionHeader title="Clinical Safety &amp; Regulatory Notice" accent="#F59E0B" />
              <div style={{
                background: 'rgba(217, 107, 82, 0.22)', border: '1px solid rgba(217, 107, 82, 0.22)',
                borderRadius: 12, padding: '18px 22px',
              }}>
                <div style={{ display: 'flex', gap: 12 }}>
                  <AlertTriangle size={18} color="#F43F5E" style={{ flexShrink: 0, marginTop: 2 }} />
                  <div>
                    <p style={{
                      margin: '0 0 12px', fontSize: 12, lineHeight: 1.75,
                      color: 'rgba(251,113,133,0.9)',
                    }}>
                      {FULL_DISCLAIMER}
                    </p>
                    <div style={{
                      fontFamily: 'var(--font-mono)', fontSize: 11,
                      color: 'rgba(251,113,133,0.6)', borderTop: '1px solid rgba(217, 107, 82, 0.22)',
                      paddingTop: 10, marginTop: 4,
                    }}>
                      {reportData.disclaimer}
                    </div>
                  </div>
                </div>
              </div>

              {/* ────── METHODOLOGY ────────────────────────── */}
              <SectionHeader title="Methodology Brief" accent="#1F7A58" />
              <div style={{
                background: 'rgba(128, 231, 184, 0.28)', border: '1px solid rgba(128, 231, 184, 0.28)',
                borderRadius: 10, padding: '16px 20px', fontSize: 12, lineHeight: 1.8,
                color: 'var(--sage)',
              }}>
                {METHODOLOGY_TEXT}
              </div>

              {/* ────── TRACEABILITY FOOTER ─────────────────── */}
              <SectionHeader title="Traceability &amp; Audit Trail" accent="#94A3B8" />
              <div style={{
                background: 'var(--cream)', border: '1px solid rgba(0,0,0,0.06)',
                borderRadius: 10, padding: '16px 20px',
                fontFamily: 'var(--font-mono)', fontSize: 11,
                color: 'var(--sage-light)',
              }}>
                <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(260px, 1fr))', gap: '8px 24px' }}>
                  {[
                    ['Case ID', reportData.case_id],
                    ['Report Generated', reportData.generated_at],
                    ['DDPM Model Version', reportData.model_versions.ddpm],
                    ['Segmentation Model Version', reportData.model_versions.segmentation],
                    ['Preprocessing Pipeline', 'NeuroPrep-v1.0'],
                    ['Reconstruction Timestamp', reportData.reconstruction?.timestamp ?? 'N/A'],
                    ['Segmentation Timestamp', reportData.segmentation?.timestamp ?? 'N/A'],
                    ['Experiment Label', `Experiment ${reportData.segmentation?.experiment ?? '-'}`],
                    ['Input Source', reportData.segmentation?.input_source ?? 'N/A'],
                    ['Data Source', selectedCaseRecord.source],
                    ['Platform', 'NeuroAI Research Platform · Capstone 2024'],
                    ['De-Identification Status', 'Confirmed · BraTS2020 Public Dataset'],
                  ].map(([k, v]) => (
                    <div key={k} style={{ display: 'flex', gap: 8, alignItems: 'flex-start' }}>
                      <span style={{ color: 'var(--sage-light)', minWidth: 180, flexShrink: 0 }}>{k}:</span>
                      <span style={{ color: 'var(--forest)', wordBreak: 'break-all' }}>{v}</span>
                    </div>
                  ))}
                </div>
                <div style={{
                  marginTop: 16, paddingTop: 12,
                  borderTop: '1px solid rgba(0,0,0,0.05)',
                  fontSize: 10, color: 'var(--sage-light)',
                  letterSpacing: '0.04em',
                }}>
                  REPORT END · NeuroAI Platform · Research Prototype · {new Date().getFullYear()} ·
                  Hash: {btoa(reportData.case_id + reportData.generated_at).slice(0, 24).toUpperCase()}
                </div>
              </div>
            </div>{/* /report-card */}

            {/* ── Bottom Print Buttons ──────────────────────── */}
            <div className="no-print" style={{ display: 'flex', gap: 10, justifyContent: 'flex-end', marginTop: 20 }}>
              <button className="btn btn-ghost btn-sm" onClick={handlePrint}>
                <Printer size={14} />
                Print / Export PDF
              </button>
              <button
                className="btn btn-primary"
                onClick={handleGenerate}
                disabled={isGenerating}
              >
                <Download size={14} />
                Regenerate
              </button>
            </div>

          </div>
        )}{/* /reportData */}

        {/* ── Bottom Disclaimer ─────────────────────────────── */}
        <DisclaimerBanner position="bottom" />
      </div>
    </>
  );
};

export default ResearchReport;
